return {
  diagnostic = {
    error = "",
    warn = "",
    warning = "",
    info = "",
    hint = "",
    ok = "",
  },
  git_diff = {
    added = "",
    ignored = "",
    modified = "",
    removed = "",
    renamed = "",
  },
  arrow = {
    up = "󰁝",
    down = "󰁅",
    left = "󰁍",
    right = "󰁔",
    top_left = "󰁛",
    top_right = "󰁜",
    bottom_left = "󰁂",
    bottom_right = "󰁃",
  },
  misc = {
    clock = "",
    debug = "",
    fold_closed = "",
    fold_open = "",
  },
  kinds = {
    Array = "",
    Boolean = "",
    Call = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Identifier = "",
    Interface = "",
    Key = "",
    Keyword = "",
    List = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
}
