return {
  diagnostic = {
    error = "",
    warn = "",
    warning = "",
    info = "",
    hint = "",
  },
  git_diff = {
    added = "",
    modified = "",
    removed = "",
  },
  arrow = {
    up = "󰁝",
    down = "󰁅",
    left = "󰁍",
    right = "󰁔",
    top_left = "󰁛",
    top_right = "󰁜",
    bottom_left = "󰁂",
    bottom_right = "󰁃",
  },
  fold = {
    close = "",
    open = "",
  },
  misc = {
    bulb = "",
    ellipsis = "⋯",
    find = "",
    location = "",
  },
  kinds = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "󰟢",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
}
