. "$HOME/.cargo/env"

export PATH=$PATH:/usr/local/texlive/2026/bin/x86_64-linux
export MANPATH=$MANPATH:/usr/local/texlive/2026/texmf-dist/doc/man
export INFOPATH=$INFOPATH:/usr/local/texlive/2026/texmf-dist/doc/info

export PATH=$PATH:$HOME/.local/bin

export GUROBI_HOME="/opt/gurobi/linux64"
export PATH="${PATH}:${GUROBI_HOME}/bin"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
export GRB_LICENSE_FILE="/opt/gurobi/gurobi.lic"

export EDITOR="nvim"
export MANPAGER="nvim +Man!"
