. "$HOME/.cargo/env"

export PATH=$PATH:/usr/local/texlive/2026/bin/x86_64-linux
export MANPATH=$MANPATH:/usr/local/texlive/2026/texmf-dist/doc/man
export INFOPATH=$INFOPATH:/usr/local/texlive/2026/texmf-dist/doc/info

export PATH=$PATH:$HOME/.local/bin

export EDITOR="nvim"
export MANPAGER="nvim +Man!"
