source /usr/share/zsh-antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle colored-man-pages
antigen bundle command-not-found
antigen bundle gh
antigen bundle git
antigen bundle git-lfs
antigen bundle npm
antigen bundle ubuntu
antigen bundle sainnhe/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle sindresorhus/pure@main
antigen bundle skywind3000/z.lua
antigen theme pure
antigen apply

export ZSH=~/.antigen/bundles/robbyrussell/oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Completions
autoload -U +X compinit && compinit

# Vi mode
bindkey -v

# Aliases
alias nvi="neovide.exe"

# Proxy
export hostip=$(ip route | grep default | awk '{print $3}')
export hostport=10809
export https_proxy="http://${hostip}:${hostport}"
export http_proxy="http://${hostip}:${hostport}"
export all_proxy="http://${hostip}:${hostport}"
alias proxy='
  export https_proxy="http://${hostip}:${hostport}";
  export http_proxy="http://${hostip}:${hostport}";
  export all_proxy="http://${hostip}:${hostport}";
  echo -e "Acquire::http::Proxy \"http://${hostip}:${hostport}\";" | sudo tee -a /etc/apt/apt.conf.d/proxy.conf > /dev/null;
  echo -e "Acquire::https::Proxy \"http://${hostip}:${hostport}\";" | sudo tee -a /etc/apt/apt.conf.d/proxy.conf > /dev/null;
  sudo npm -g config set proxy http://${hostip}:${hostport};
  sudo npm -g config set https-proxy http://${hostip}:${hostport};
  git config --global http.proxy ${hostip}:${hostport};
  git config --global https.proxy ${hostip}:${hostport};
  sudo snap set system proxy.http="http://${hostip}:${hostport}"
  sudo snap set system proxy.https="http://${hostip}:${hostport}"
'
alias unproxy='
  unset https_proxy;
  unset http_proxy;
  unset all_proxy;
  sudo sed -i -e '/Acquire::http::Proxy/d' /etc/apt/apt.conf.d/proxy.conf;
  sudo sed -i -e '/Acquire::https::Proxy/d' /etc/apt/apt.conf.d/proxy.conf;
  sudo npm -g config rm proxy;
  sudo npm -g config rm https-proxy;
  git config --global --unset http.proxy;
  git config --global --unset https.proxy;
  sudo snap set system proxy.http=""
  sudo snap set system proxy.https=""
'
