name: lint
on:
  push:
    paths:
      - '**.lua'
  pull_request:
    paths:
      - '**.lua'
  workflow_dispatch:

jobs:
  stylua:
    name: StyLua
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Lint with StyLua
        uses: JohnnyMorganz/stylua-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config-path nvim/.stylua.toml --check nvim/

  luacheck:
    name: luacheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Lint with luacheck
        uses: lunarmodules/luacheck@v0
        with:
          args: --config nvim/.luacheckrc nvim/
